### ISSUE TITLE
NPE on SSLLogger with ECDHE ciphers

### ISSUE THREAD

**Issue by ask4gilles** [zulu-openjdk/zulu-openjdk#109]
Hi,

We are facing this exception with the following configuration:

JDK version:
`zulu11.43.56-sa-jdk11.0.9.1-linux_x64`

(Spring boot `2.5.4`, Tomcat: `9.0.52`)

Tomcat SSL configuration:

```
server.ssl.enabled=true
server.ssl.enabled-protocols=TLSv1.2,TLSv1.3
server.ssl.ciphers=TLS_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_CCM,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_DSS_WITH_AES_256_CBC_SHA256,TLS_DHE_DSS_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_256_CCM
server.ssl.client-auth=need
```

```
j.l.NullPointerException: null
at s.s.ssl.SSLLogger.log(SSLLogger.java:182)
at s.s.ssl.SSLLogger.warning(SSLLogger.java:162)
at s.s.s.KeyShareExtension$CHKeyShareConsumer.consume(KeyShareExtension.java:374)
at s.s.ssl.SSLExtension.consumeOnLoad(SSLExtension.java:554)
at s.s.s.SSLExtensions.consumeOnLoad(SSLExtensions.java:189)
at s.s.s.ClientHello$T13ClientHelloConsumer.consume(ClientHello.java:1164)
at s.s.s.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:852)
at s.s.s.ClientHello$ClientHelloConsumer.consume(ClientHello.java:813)
at s.s.ssl.SSLHandshake.consume(SSLHandshake.java:392)
at s.s.s.HandshakeContext.dispatch(HandshakeContext.java:444)
at s.s.s.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1074)
at s.s.s.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
at j.s.AccessController.doPrivileged(AccessController.java)
at s.s.s.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1008)
at o.a.t.u.n.SecureNioChannel.tasks(SecureNioChannel.java:429)
at o.a.t.u.n.SecureNioChannel.handshakeUnwrap(SecureNioChannel.java:493)
at o.a.t.u.n.SecureNioChannel.handshake(SecureNioChannel.java:217)
at o.a.t.u.n.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1702)
at o.a.t.u.n.SocketProcessorBase.run(SocketProcessorBase.java:49)
at o.a.t.u.t.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
at o.a.t.u.t.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
at o.a.t.u.t.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:834)
```
From the stacktrace, it seems related to `ECDHE` ciphers (?)

Please advise, thanks!

**Comment by AntonKozlov** [comment]
Hi! The Zulu version does not look like a build provided in the docker images. Please contact https://www.azul.com/support/ to clarify details. Thanks.
