### ISSUE TITLE
NullPointer in javac Zulu 11.0.17 2022-10-18 LTS

### ISSUE THREAD

**Issue by gdoenlen** [zulu-openjdk/zulu-openjdk#168]
Honestly not sure if this is the spot to report to this but after updating to the most recent Zulu 11 JDK release I'm receiving a NPE inside of javac.

Output of `java --version`:

```
openjdk 11.0.17 2022-10-18 LTS
OpenJDK Runtime Environment Zulu11.60+19-CA (build 11.0.17+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.60+19-CA (build 11.0.17+8-LTS, mixed mode)
```

Exception:

```
[error] compiler message file broken: key=compiler.misc.msg.bug arguments=11.0.17, {1}, {2}, {3}, {4}, {5}, {6}, {7}
[error] java.lang.NullPointerException
[error]         at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitApply(Flow.java:1235)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1650)
[error]         at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:398)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Flow$LambdaFlowAnalyzer.visitLambda(Flow.java:1430)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCLambda.accept(JCTree.java:1827)
[error]         at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:398)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.analyzeTree(Flow.java:1327)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Flow.analyzeLambdaThrownTypes(Flow.java:252)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitLambda(Attr.java:2615)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCLambda.accept(JCTree.java:1827)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[error]         at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr$4.complete(DeferredAttr.java:376)
[error]         at jdk.compiler/com.sun.tools.javac.comp.ArgumentAttr$ArgumentType.complete(ArgumentAttr.java:364)
[error]         at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr$DeferredType.check(DeferredAttr.java:337)
[error]         at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr$DeferredType.check(DeferredAttr.java:323)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Resolve$MethodResultInfo.check(Resolve.java:1060)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Resolve$4.checkArg(Resolve.java:887)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Resolve$AbstractMethodCheck.argumentsAcceptable(Resolve.java:775)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Resolve$4.argumentsAcceptable(Resolve.java:896)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Infer.instantiateMethod(Infer.java:181)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Resolve.rawInstantiate(Resolve.java:605)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Resolve.checkMethod(Resolve.java:644)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.checkMethod(Attr.java:4131)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.checkIdInternal(Attr.java:3924)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.checkMethodIdInternal(Attr.java:3825)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.checkId(Attr.java:3814)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3707)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2130)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitApply(Attr.java:2006)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1650)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:702)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitExec(Attr.java:1773)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1468)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:724)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStats(Attr.java:743)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1294)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1036)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:724)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStats(Attr.java:743)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1294)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1036)
[error]         at jdk.compiler/com.sun.tools.javac.comp.ArgumentAttr.visitTree(ArgumentAttr.java:207)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$Visitor.visitBlock(JCTree.java:3086)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1036)
[error]         at jdk.compiler/com.sun.tools.javac.comp.ArgumentAttr.attribArg(ArgumentAttr.java:197)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:653)
[error]         at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr.attribSpeculative(DeferredAttr.java:501)
[error]         at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr.attribSpeculative(DeferredAttr.java:483)
[error]         at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr.attribSpeculativeLambda(DeferredAttr.java:458)
[error]         at jdk.compiler/com.sun.tools.javac.comp.ArgumentAttr.lambda$visitLambda$3(ArgumentAttr.java:296)
[error]         at jdk.compiler/com.sun.tools.javac.comp.ArgumentAttr.processArg(ArgumentAttr.java:242)
[error]         at jdk.compiler/com.sun.tools.javac.comp.ArgumentAttr.visitLambda(ArgumentAttr.java:294)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCLambda.accept(JCTree.java:1827)
[error]         at jdk.compiler/com.sun.tools.javac.comp.ArgumentAttr.attribArg(ArgumentAttr.java:197)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:653)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribArgs(Attr.java:751)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1997)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1650)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3584)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2130)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitApply(Attr.java:2006)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1650)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:702)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitExec(Attr.java:1773)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1468)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:724)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStats(Attr.java:743)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1294)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1036)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:724)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStats(Attr.java:743)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1294)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1036)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[error]         at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr.attribSpeculative(DeferredAttr.java:501)
[error]         at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr.attribSpeculative(DeferredAttr.java:483)
[error]         at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr.attribSpeculativeLambda(DeferredAttr.java:458)
[error]         at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr$DeferredAttrNode$StructuralStuckChecker.canLambdaBodyCompleteNormally(DeferredAttr.java:875)
[error]         at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr$DeferredAttrNode$StructuralStuckChecker.visitLambda(DeferredAttr.java:853)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCLambda.accept(JCTree.java:1827)
[error]         at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr$DeferredAttrNode$StructuralStuckChecker.complete(DeferredAttr.java:807)
[error]         at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr$DeferredType.check(DeferredAttr.java:337)
[error]         at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr$DeferredAttrNode.process(DeferredAttr.java:754)
[error]         at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr$DeferredAttrContext.complete(DeferredAttr.java:601)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Resolve.rawInstantiate(Resolve.java:620)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Resolve.selectBest(Resolve.java:1563)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Resolve.findMethodInScope(Resolve.java:1733)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1802)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1776)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Resolve.findFun(Resolve.java:1933)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Resolve$9.doLookup(Resolve.java:2622)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Resolve$BasicLookupHelper.lookup(Resolve.java:3293)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3543)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3528)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Resolve.resolveMethod(Resolve.java:2618)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitIdent(Attr.java:3495)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2264)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitApply(Attr.java:2006)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1650)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3584)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2130)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitApply(Attr.java:2006)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1650)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitReturn(Attr.java:1866)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1562)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:724)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStats(Attr.java:743)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1294)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1036)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:724)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1098)
[error]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:866)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:724)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:4694)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4585)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4514)
[error]         at jdk.compiler/com.sun.tools.javac.comp.Attr.attrib(Attr.java:4459)
[error]         at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1337)
[error]         at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
[error]         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
[error]         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
[error]         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
[error]         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
```

**Comment by it-mak** [comment]
Hello, thank you for the request. I don't have any problems. Can you provide more details?

```
docker run -it azul/zulu-openjdk:11 java --version
openjdk 11.0.17 2022-10-18 LTS
OpenJDK Runtime Environment Zulu11.60+19-CA (build 11.0.17+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.60+19-CA (build 11.0.17+8-LTS, mixed mode)
```

**Comment by AntonKozlov** [comment]
@gdoenlen Could you share .java file that triggers the problem?

**Comment by gdoenlen** [comment]
Unfortunately, no I cannot share the file. I had debugged javac and its null pointing [here](https://github.com/openjdk/jdk/blob/jdk-11%2B28/src/jdk.compiler/share/classes/com/sun/tools/javac/comp/Flow.java#L1235) because the `type` field is null.

According the debugger the method its on it is just an interface method, which is being implemented by an anonymous class. I'll try to debug tomorrow to see why its not setting the type.

**Comment by gdoenlen** [comment]
I haven't been able to get a reproducible case for you, but it's null pointing because the compiler fails to recognize the type of the lambda here:

```java
Functions.promiseWithContext(() -> {
      ModuleLoader.withModuleClassLoader(
             AdapterUtils.ADAPTER,
             () -> task.execute(progress, file, user, ignoreWarnings) <-- this lambda's type is  not recognized properly and results in NPE
      );
});
```

Lifting this lambda into the type that is declared for `withModuleClassLoader` the compiler correctly recognizes the type and that it throws:

```java
ModuleLoaderContextOperation<?> op = () -> task.execute(progress, file, user, ignoreWarnings);
ModuleLoader.withModuleClassLoader(
     AdapterUtils.ADAPTER,
     op
 );
```


```sh
[error] unreported exception capture#1 of ?; must be caught or declared to be thrown
[error] ModuleLoader.withModuleClassLoader(
[error]                     AdapterUtils.ADAPTER,
[error]                     op
[error]                 )
```


I think this is happening because the `ModuleLoaderContextOperation` functional interface declares to throw `Throwable` and the `Functions.promiseWithContext` only declares that it can throw `Exception`.

Here are the definitions of the functions:

```java
    public interface ModuleLoaderContextOperation<TException extends Throwable> {
        void op() throws TException;
    }
    
    @FunctionalInterface
    public interface ExceptionalSupplier<T, E extends Exception> {
        T get() throws E;
    }
    
    public static <T> T promiseWithContext(ExceptionalSupplier<T> supp) {
        try {
            supp.get();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```

Again I haven't been able to get a generic reproducible case, but I hope this helps.

**Comment by schlosna** [comment]
See https://bugs.openjdk.org/browse/JDK-8222251

**Comment by AntonKozlov** [comment]
I really hope JDK-8222251 to help, but I had no time to verify this against the information above (thanks, BTW!).

Could you check a latest build from the dev branch of jdk11u with that fix included?
https://github.com/AntonKozlov/jdk11u-dev/actions/runs/3416968784

**Comment by gdoenlen** [comment]
Apologize for the delay. That back port did help and compilation is successful now after using the linked build.

Thank you @AntonKozlov!
