### ISSUE TITLE
No FileSystem for scheme \"file\" When working with Hadoop and ParquetWriter in debian-17.0.5 image

### ISSUE THREAD

**Issue by sheinbergon** [zulu-openjdk/zulu-openjdk#169]
```
Caused by: org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme \"file\"
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3443)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at org.apache.parquet.hadoop.util.HadoopOutputFile.fromPath(HadoopOutputFile.java:58)
	at org.apache.parquet.hadoop.ParquetWriter$Builder.build(ParquetWriter.java:677)
```

This didn't occur until tag `17` was updated to point to `17.0.5-1`. I can confirm reverting back to `17.0.4-1` resolved the issue.
Any idea on what might be causing this in issue in the the new docker image?

The file I'm trying to create is under `/tmp`. (temp file). Dependencies are fine (all of the required dependncies are present)

**Comment by it-mak** [comment]
Thank you for the issue, we will analyze the case

**Comment by AntonKozlov** [comment]
Hi @sheinbergon, do you have a reproducer you could share? Because the internet has a few similar problem reports. A reproducer would be very helpful to ensure we are facing the same problem.
