### ISSUE TITLE
java.lang.UnsatisfiedLinkError using azul/zulu-openjdk-alpine:11 docker image

### ISSUE THREAD

**Issue by p-bakker** [zulu-openjdk/zulu-openjdk#32]
See stacktrace below. Not sure if there are some steps I missed to prevent this from happening or if there's an issue with the image

```
java.lang.reflect.InvocationTargetException 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
Caused by: java.lang.UnsatisfiedLinkError: /usr/lib/jvm/zulu11.2.3-jdk11.0.1-linux_musl_x64/lib/libawt_xawt.so: Error loading shared library libXtst.so.6: No such file or directory (needed by /usr/lib/jvm/zulu11.2.3-jdk11.0.1-linux_musl_x64/lib/libawt_xawt.so) 
at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method) 
at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430) 
at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487) 
at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684) 
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617) 
at java.base/java.lang.Runtime.load0(Runtime.java:767) 
at java.base/java.lang.System.load(System.java:1831) 
at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method) 
at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430) 
at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487) 
at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684) 
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638) 
at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829) 
at java.base/java.lang.System.loadLibrary(System.java:1867) 
at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1395) 
at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1393) 
at java.base/java.security.AccessController.doPrivileged(Native Method) 
at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1392) 
at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1425) 
at java.desktop/java.awt.EventQueue.isDispatchThread(EventQueue.java:1086) 
at java.desktop/javax.swing.SwingUtilities.isEventDispatchThread(SwingUtilities.java:1493) 
```

**Comment by p-bakker** [comment]
Talked to Azul support: adding the following command to your Docker file would fix this:
``` 
RUN apk add --update --no-cache \
	libxtst \
	libxi
```

**Comment by sgrinev** [comment]
resolved by using apk repository for the latest alpine images

**Comment by p-bakker** [comment]
I just upgraded to use the `azul/zulu-openjdk-alpine:14` image and thought I would be able to remove the bit below from my docker file, given the previous comment that the issue is resolved by `using apk repo for the latest alpine images`

> ```
> RUN apk add --update --no-cache \
> 	libxtst \
> 	libxi
> ```

However, after removing libxtst and libxi being added in the dockerfile, the error I had previously with the alpine 11 image started happening again:
```
java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Caused by: java.lang.UnsatisfiedLinkError: /usr/lib/jvm/zulu14.28.21-ca-jdk14.0.1-linux_musl_x64/lib/libawt_xawt.so: Error loading shared library libXtst.so.6: No such file or directory (needed by /usr/lib/jvm/zulu14.28.21-ca-jdk14.0.1-linux_musl_x64/lib/libawt_xawt.so)
at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2452)
at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2508)
at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2704)
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2637)
at java.base/java.lang.Runtime.load0(Runtime.java:745)
at java.base/java.lang.System.load(System.java:1871)
at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2452)
at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2508)
at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2704)
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2658)
at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:807)
at java.base/java.lang.System.loadLibrary(System.java:1907)
at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1380)
at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1378)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1377)
at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1410)
at java.desktop/java.awt.EventQueue.isDispatchThread(EventQueue.java:1086)
at java.desktop/javax.swing.SwingUtilities.isEventDispatchThread(SwingUtilities.java:1493)
...
```

Did I misinterpret the previous comment or is there still (or again) an issue?

**Comment by sgrinev** [comment]
looks like a bug, i'll check

**Comment by sgrinev** [comment]
Unfortunately, we don't have repository installation bundles for OpenJDK14 (because it's a short release), so the [docker imag](https://github.com/zulu-openjdk/zulu-openjdk/blob/master/alpine/14.0.1-14.28.21/Dockerfile)e is built old-way from the archive so the fix is not applicable.

It will be good again in the upcoming OpenJDK 15 :)
